# Generated by Django 4.2.8 on 2023-12-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcount',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
